### ISSUE TITLE
Create flock-os-builder OVA with ubuntu-2204 for gcloud

### ISSUE THREAD

**Issue by markope** [RecordEvolution/ReswarmOS#101]
... to be able to use the ova as base image for a VM in gcloud the max supported ubuntu is 2204.

The current 2310 version does not work.

Machine Image can be created with 

```
gcloud beta compute machine-images import flock-os-builder \
    --source-uri=gs://flockos-vm/Ubuntu2204.ova \
    --os=ubuntu-2204
```

**Comment by DewitteRuben** [comment]
Readme for setup can be found here:
https://github.com/RecordEvolution/ReswarmOS/blob/master/flockos-vm-setup.md
